version: '3.1'
services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_data:/var/jenkins_home
        ports:
            - "8080:8080"
            - "50000:50000"

volumes:
  jenkins_data: