version: '3.1'
services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_home:/var/jenkins_home
        ports:
            - "8080:8080"
            - "50000:50000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/login || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s

volumes:
  jenkins_home: